name: AutoCreative
author: TheNewHEROBRINE
version: 2.0.0
main: TheNewHEROBRINE\AutoCreative\Main
api: 3.0.0

#commands:
 #survival:
  #aliases: ["s"]
 #creative:
  #aliases: ["c"]

permissions:
 autocreative:
  children:
   autocreative.exempt:
    default: op